[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 4 --threads 2 --worker-class gevent --timeout 120 --keep-alive 5 --log-level info --access-logfile - --error-logfile -"

[variables]
PYTHONUNBUFFERED = "1"
